Updates so that correct domain is sat for local to #189
NDLANO/auth pull request #9
Opened 2017-01-24 16:25 UTC by chrpeter

2017-01-25 07:18 UTC, kstigen requested changes

2017-01-25 07:18 UTC, kstigen commented on src/main/scala/no/ndla/auth/AuthProperties.scala
> +  lazy val Domain = Map(
Hvorfor legger vi til et eget map her i stedet for å oppdatere Domains i network?

2017-01-26 16:07 UTC, chrpeter commented on src/main/scala/no/ndla/auth/AuthProperties.scala
> +  lazy val Domain = Map(
Det viste jeg ikke, fikser dette. Local må vel endres til proxy.ndla-local

2017-01-30 09:45 UTC, runesto commented on src/main/scala/no/ndla/auth/AuthProperties.scala
> +  lazy val Domain = Map(
Merk at det som legges i `Domains` i `network` må gjelde for alle komponenter (eller i hvert fall de fleste). Betyr det at alle sammen skal bruke `proxy.ndla-local` som host for all lokal-kommunikasjon?

2017-01-30 12:54 UTC, chrpeter commented on src/main/scala/no/ndla/auth/AuthProperties.scala
> +  lazy val Domain = Map(
Skal ha byttet til network biblotektet nå (v. 0.8)

2017-01-31 12:14 UTC, kstigen approved these changes

2017-01-31 12:44 UTC, merged